### ISSUE TITLE
/bat lookup [Name] Formatting

### ISSUE THREAD

**Issue by B1acksheep** [alphartdev/BAT-WebInterface#14]
Since Minecraft 1.8 there is the possibility to use [Hover-/Click-Events.](www.spigotmc.org/wiki/the-chat-component-api/)

Lookup profile:
```
 ---- Statisiken Picard68 ----
Offline
Aktueller Status : 
  Gebannt auf : (global)
  IP-Gebannt auf : keine
  SGemutet auf : keine
  IP-Gemutet auf : keine
Erster Login : 09-12-2015 um 18:09
Zuletzt online : 29-12-2015 um 12:47
Letzte IP : 00.000.00.000
Vergangenheit : 1 bans
            1 mutes
            0 kicks
Letzten drei Bemerkungen: 
  #120 Warning Inhalt: nicht nachgepflanzt in einer stadt 2 Datum: 22-12-2015 um 18:57 Erstellt von: xhera#112 Warning Inhalt: Nicht nachgepflanzt 1 Datum: 19-12-2015 um 18:26 Erstellt von: Blacksheep92#111 Warning Inhalt: Griefing in Minera 4 Datum: 19-12-2015 um 17:51 Erstellt von: Blacksheep92
Vergangene Namen : Picard68
UUID : d5980c48624c45628b26b2ca9d4fd166
---- Statistiken Picard68 ----
```

My suggestions:

* Add a ClickEvent for "---- Statisiken Picard68 ----" to visit the website
* Add a HoverEvent for "---- Statisiken Picard68 ----" with UUID, LastNames, IP
* Add a HoverEvent for "Offline" with firstlogin & lastlogin
* Add the reason, time & "creator" of an ban/mute as a HoverEvent  
* Warning Example
 * Text:
 * #120 Reason: nicht nachgepflanzt in einer stadt 2
 * As HoverEvent: 
  * Datum: 22-12-2015 um 18:57 
  * Erstellt von: Hera
 * And add line breaks ;)

**Comment by alphartdev** [comment]
Need to be move to BAT plugin repo.
